### ISSUE TITLE
Add documentation about ML

### ISSUE THREAD

**Issue by knighthood-18** [knighthood-18/Documentation-WebPage#1]
Add your blog below already existing documentation. Add references below. And make all the necessary changes.

**Comment by Kavit-Shah** [comment]
Assign this issue to me.

**Comment by Chirag-v09** [comment]
Hello, where and how I suppose to add documentation?

**Comment by knighthood-18** [comment]
> Hello, where and how I suppose to add documentation?

In the html file. you can add documentation about some other topic as this topic has already been completed.
